//This object has the sx,sy,swidth,sheight of all sprites

export default {
    playerShip:{
        x:745,
        y:67,
        width:188,
        height:131,
        img:'../img/index.png'

    },
    miniRocket:{
        x:906,
        y:606,
        width:20,
        height:71,
        img:'../img/index.png'

    },
    rocket:{
        x:851,
        y:567,
        width:41,
        height:129,
        img:'../img/index.png'
    },
    circleRocket:{
        x:530,
        y:718,
        width:70,
        height:68,
        img:'../img/index.png',
        type:'circleRocket'
    },
    asteroid:{
        x:191,
        y:732,
        width:61,
        height:60,
        img:'../img/index.png'
    },
    gift:{
        x:447,
        y:99,
        width:68,
        height:63,
        img:'../img/index.png',
        type:'gift'
    },
    miniShipEnemy:{
        x:297,
        y:474,
        width:122,
        height:127,
        img:'../img/enemy.png',
        type:'miniShipEnemy'
    },
    shipEnemy:{
        x:430,
        y:474,
        width:200,
        height:151,
        img:'../img/enemy.png',
        type:'shipEnemy'
    },
    miniRocketEnemy:{
        x:111,
        y:485,
        width:21,
        height:72,
        img:'../img/enemy.png',
        type:'miniRocketEnemy'

    },
    cannonEnemy1:{
        x:157,
        y:259,
        width:68,
        height:126,
        img:'../img/enemy.png',
        type:'cannonEnemy1'

    },
    cannonEnemy2:{
        x:251,
        y:258,
        width:68,
        height:117,
        img:'../img/enemy.png',
        type:'cannonEnemy2'

    },
    explosion:{
        x:0,
        y:0,
        width:180,
        height:180,
        img:'../img/explosion.png',
        type:'explosion'
    }
}