//This object has the sx,sy,swidth,sheight of all sprites

export default {
    playerShip:{
        x:6,
        y:6,
        width:188,
        height:131,
        img:'../img/img.png'

    },
    miniRocket:{
        x:361,
        y:52,
        width:20,
        height:71,
        img:'../img/img.png'

    },
    rocket:{
        x:306,
        y:13,
        width:41,
        height:129,
        img:'../img/img.png'
    },
    circleRocket:{
        x:775,
        y:189,
        width:70,
        height:68,
        img:'../img/img.png',
        type:'circleRocket'
    },
    asteroid:{
        x:697,
        y:193,
        width:61,
        height:60,
        img:'../img/img.png'
    },
    gift:{
        x:865,
        y:193,
        width:68,
        height:63,
        img:'../img/img.png',
        type:'gift'
    },
    miniShipEnemy:{
        x:564,
        y:186,
        width:122,
        height:127,
        img:'../img/img.png',
        type:'miniShipEnemy'
    },
    shipEnemy:{
        x:765,
        y:8,
        width:200,
        height:151,
        img:'../img/img.png',
        type:'shipEnemy'
    },
    miniRocketEnemy:{
        x:375,
        y:191,
        width:21,
        height:72,
        img:'../img/img.png',
        type:'miniRocketEnemy'

    },
    cannonEnemy1:{
        x:8,
        y:174,
        width:68,
        height:126,
        img:'../img/img.png',
        type:'cannonEnemy1'

    },
    cannonEnemy2:{
        x:102,
        y:173,
        width:68,
        height:117,
        img:'../img/img.png',
        type:'cannonEnemy2'

    },
    explosion:{
        x:316,
        y:316,
        width:180,
        height:180,
        img:'../img/img.png',
        type:'explosion'
    }
}